#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]
# to see what versions are available: https://pypi.org/pypi/robotpy/json
# Version of robotpy this project depends on
robotpy_version = "2025.3.1.1"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all"
    "apriltag",
    # "commands2"
    "cscore",
    "navx",
    # "pathplannerlib"
    # "phoenix5",
    "phoenix6",
    # "playingwithfusion"
    "rev",
    # "romi"
    # "sim"
]

# Other pip packages to install
requires = [
    "photonlibpy==2025.2.1",
    "photonlibpy==2025.1.1",
    "debugpy==1.8.11",
    #"phoenix6==25.1.0",
    "robotpy-playingwithfusion == 2025.0.0",
]
